#!/bin/sh
cd "$(dirname "$0")"

# Test running lisp-system:
general_test () {
local PROVIDE="$1"
local IF_OK="$2"
printf "test $PROVIDE ... "
local RESULT="$($PROVIDE 2>/dev/null | tail -n1)"

if test "ALREADY." = "$RESULT";then
printf "OK(ALREADY)";echo;return 0;
fi

if test "OK." = "$RESULT";then
    printf "OK";echo;

    if test "$IF_OK" != "";then 
	general_test "$IF_OK";
    fi 	

return 0;
fi

echo FAIL;return 1;
}

test_provide_lisp () {
general_test "./provide-lisp"
}

test_provide_emacs () {
general_test "./provide-emacs"
}

# Test running lisp-system:
test_run_lisp () {
printf "test ./run-lisp ... "
if test "$(./run-lisp --eval "(progn (format t \"~%Test running lisp-system~%Printed symbol SOME:~%\") (princ 'SYMBOL) (terpri))" \
 --eval "(quit)" | tail -n1)" = "SYMBOL";then
printf OK;
else echo FAIL;return 1;
fi
echo
}

general_test ./provide-lisp
test_run_lisp
general_test ./provide-emacs ./remove-emacs	
general_test ./provide-slime ./remove-slime