#!/bin/sh
cd "$(dirname "$0")"

### Getting command line without running lisp ###
# If GET_CMD_P=yes file sh/run_lisp.sh then only doing output command line
#################################

GET_CMD_P=$GET_CMD_P sh/run-lisp.sh "$@"

