#!/bin/sh

get_lisp_param () {
local REST_PARAM_PART="$1"
echo $(get_spec_val $CUR_LISP _$REST_PARAM_PART)
}

ALL_LISP_PARAMS="
VERSION
HOME_SITE
ARCH
OS
ENABLE_QUICKLISP
DIRNAME
LISPS_DIR
DIR
RELATIVE_PATH
LISPS_SOURCES
SOURCES_DIRNAME
LIB_DEPS
NO_LIB_DEPS_HINT
LISPS_COMPILERS
COMPILER_DIRNAME
NO_BUILDING_P
SELF_COMPILATION_P
LOAD_OPTION
PREBUILD_CMD
BUILD_CMD
INSTALL_CMD
HOME_VAR_NAME
BIN_DIR
CORE_BIN_DIR
BIN_BUILD_RESULT
BIN_IN_SOURCES
BIN_ARCHIVE
BIN_URL
BIN_POST_DOWNLOAD_CMD
RENAME_BIN_DOWNLOAD
RENAME_SRC_DOWNLOAD
SOURCE_ARCHIVE
SOURCE_URL
SRC_POST_DOWNLOAD_CMD
RENAME_SRC_DOWNLOAD
SRC_ARCHIVE_TYPE
BIN_ARCHIVE_TYPE
SRC_ARCHIVE_LOWERING_P
BIN_ARCHIVE_LOWERING_P
DEPS_ON_TOOLS"

for param in $ALL_LISP_PARAMS;
do 
    eval LISP_${param}="\"$(get_lisp_param $param)\""; 
done
