#!/bin/sh

LINK="$1"
BEGIN_PATH="$2"
if [ "$BEGIN_PATH" = "" ];then
    BEGIN_PATH=$(dirname $LINK);
    if [ "$BEGIN_PATH" = "" ] || [ "$BEGIN_PATH" = "." ];then
	BEGIN_PATH=$PWD;
    fi
fi

fst_char () {
echo $1 | cut -c 1
}

abs_path_p () {
local TMP
TMP=$(fst_char $1)
if [ $TMP ]; then 
  if [ "$TMP" = "/" ];
  then echo "yes";
  else echo "no";
  fi
fi
}

if [ "$(readlink $LINK)" = "" ]; then 
   if [ "abs_path_p $LINK" = "yes" ]; then
       echo "$LINK"; 
   else
       echo "$BEGIN_PATH/$LINK";
   fi
   exit 0; 
else    
    while :; do
	LINK="$(readlink $LINK)";	
	if [ "$(abs_path_p $LINK)" = "no" ]; then
	    LINK="$BEGIN_PATH/$LINK";
	fi
	cd $(dirname $LINK);
	if [ "$(readlink $LINK)" = "" ]; then 
	    echo "$LINK";
	    exit 0;
	fi
    done
fi
