#!/bin/sh
cd $(dirname $0)
. ./includes.sh

### Call build_tool ###
local ARCHIVE_PATH=$ARCHIVES/$EMACS_ARCHIVE
local TMP_TOOL_DIR=$TMP/emacs-compiling
local EXTRACT_SCRIPT="tar -xzvf"
local RESULT_DIR=$UTILS/$TOOLS_DIRNAME/$EMACS_TOOL_DIR
local COMPILING_EXTRA_PARAMS="$EMACS_COMPILING_EXTRA_ARGS"
local MES_ARCHIVE_CHECK_FAIL="
ERROR: archive $ARCHIVE_PATH does not exist!

FAILED."

local MES_BUILD_FAIL="
ERROR: Building tool EMACS failed.

FAILED."

PRE_BUILD_CMD="$EMACS_PRE_BUILD_CMD"

build_tool "$ARCHIVE_PATH" "$TMP_TOOL_DIR" "$EXTRACT_SCRIPT" "$RESULT_DIR" \
"$COMPILING_EXTRA_PARAMS" "$MES_ARCHIVE_CHECK_FAIL" "$MES_BUILD_FAIL" "$PRE_BUILD_CMD"
